version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: fplhub
      MYSQL_ROOT_PASSWORD: passwordisgod
      MYSQL_USER: fplhub
      MYSQL_PASSWORD: passwordisgod
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_data:

