"""added cookies last updated field to fpl manager session table

Revision ID: 09419a214329
Revises: c01a7b7fd53b
Create Date: 2024-10-21 20:18:31.372275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09419a214329'
down_revision = 'c01a7b7fd53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fpl_manager_sessions', sa.Column('cookies_last_updated', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fpl_manager_sessions', 'cookies_last_updated')
    # ### end Alembic commands ###