"""modify cookies field to text from varchar

Revision ID: 2e1bfb02ca22
Revises: 45be14cc0e7f
Create Date: 2024-10-30 21:54:52.944536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e1bfb02ca22'
down_revision = '45be14cc0e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fpl_scraper_accounts', 'cookies',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fpl_scraper_accounts', 'cookies',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###