"""renamed fpl manager sessions table to fpl scraper accounts

Revision ID: 45be14cc0e7f
Revises: d7c0bd60d919
Create Date: 2024-10-29 22:03:11.098668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45be14cc0e7f'
down_revision = 'd7c0bd60d919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fpl_scraper_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('manager_id', sa.String(length=255), nullable=False),
    sa.Column('cookies', sa.String(length=255), nullable=False),
    sa.Column('in_use', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.TIMESTAMP(), nullable=True),
    sa.Column('cookies_last_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fpl_manager_sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fpl_manager_sessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('manager_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cookies', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('in_use', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('last_used', mysql.TIMESTAMP(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('cookies_last_updated', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('fpl_scraper_accounts')
    # ### end Alembic commands ###