"""add_live_bonus_points_column_player_fixtures_table

Revision ID: 57f9d6813d23
Revises: d15f449cf442
Create Date: 2025-01-06 14:33:28.148113

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '57f9d6813d23'
down_revision = 'd15f449cf442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Not sure if this after is even doing anything 
    op.add_column('player_fixtures', sa.Column('live_bonus_points', sa.Integer(), nullable=True, after='red_cards'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_fixtures', 'live_bonus_points')
    # ### end Alembic commands ###
