"""created fpl manager sessions table

Revision ID: c01a7b7fd53b
Revises: 6bda774ca8e4
Create Date: 2024-10-21 19:49:18.295187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01a7b7fd53b'
down_revision = '6bda774ca8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fpl_manager_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('manager_id', sa.String(length=255), nullable=False),
    sa.Column('cookies', sa.String(length=255), nullable=False),
    sa.Column('in_use', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.TIMESTAMP(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fpl_manager_sessions')
    # ### end Alembic commands ###