"""added form and price to player model

Revision ID: d15f449cf442
Revises: 2e1bfb02ca22
Create Date: 2024-12-22 16:01:12.400092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15f449cf442'
down_revision = '2e1bfb02ca22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('players', sa.Column('form', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'price')
    op.drop_column('players', 'form')
    # ### end Alembic commands ###