"""added nullable fields to fpl manager session table

Revision ID: d7c0bd60d919
Revises: 09419a214329
Create Date: 2024-10-22 19:54:11.626864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7c0bd60d919'
down_revision = '09419a214329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fpl_manager_sessions', 'last_used',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('fpl_manager_sessions', 'cookies_last_updated',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fpl_manager_sessions', 'cookies_last_updated',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('fpl_manager_sessions', 'last_used',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###